---
title: "BLH Gut Diversity"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

What is this analysis about?

### Summary of Results
* 

```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(cowplot) # Needed for publication-quality ggplots
library(vegan)
library(gamm4)


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/gut_contents_full.csv")



```


```{r Data_Wrangling, echo = F, comment = ""}

dat1 <- dat1 %>% 
  filter(!is.na(BCTV)) %>% 
  mutate(Date = as.Date(Date, origin = "1899-12-30"),
         extraction_date = as.Date(extraction_date,
                                   origin = "1899-12-30"),
         across(c(BLH_ID, type, family, common_name, Terpene,
                genus, organism, primer, time_period,
                region, site_name, host_plant, BCTV), factor),
         Terpene = factor(case_when(
           Terpene == "" ~ "none",
           Terpene == "None" ~ "none",
           TRUE ~ Terpene
         )),
         host_plant = factor(case_when(
           host_plant == "Hemp" ~ "Hemp",
           host_plant == "Hops" ~ "Hops",
           host_plant == "Carrot" ~ "Carrot",
           TRUE ~ "Potato"
         ), levels = c("Potato", "Carrot", "Hemp", "Hops"))) %>% 
  # correcting typos in time_period
  mutate(time_period = case_when(
    time_period == " August" ~ "August",
    time_period == " April" ~ "April",
    time_period == " July" ~ "July",
    time_period == " June" ~ "June",
    time_period == " March" ~ "March",
    time_period == " May" ~ "May",
    time_period == " October" ~ "October",
    TRUE ~ time_period),
         time_period = factor(time_period,
                              levels = c("March", "April", "May",
                                         "June", "July", "August",
                                         "October")))


### Diversity
plant_div_fun <- function(data, blh_id){
  data %>% 
    filter(BLH_ID = blh_id) %>% 
    group_by(genus) %>% 
    tally(name = "plant_count") %>% 
    pivot_wider(names_from = genus,
              values_from = plant_count,
              values_fill = list(plant_count = 0)) %>% 
    column_to_rownames("site") %>% 
    diversity()
}

plant_div <- levels(dat1$BLH_ID) %>% 
  map(~ plant_div_fun(dat1, blh_id = .x))

names(plant_div) <- levels(dat1$BLH_ID)




```


```{r Graph_name, echo = F}

# Put each graph in a separate code block with a different name

```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


